---

# postgresql_db seems unable to look up db dump file
# relative to the role, so create a copy in /tmp
- name: Create copy of db schema
  copy:
    src: mud.sql
    dest: /tmp/mud.sql

- name: Create mud user in postgres
  postgresql_user:
    name: mud
    password: "{{ mud_pg_password }}"
    login_user: postgres
  become: true
  become_user: postgres

- name: Grant local access to mud
  postgresql_pg_hba:
    dest: /etc/postgresql/13/main/pg_hba.conf
    contype: local
    users: mud
    databases: mud
    method: md5
    state: present
  become: true

# https://www.postgresql.org/docs/13/app-pg-ctl.html
- name: Reload pg_hba.conf configuration
  shell: pg_ctlcluster 13 main reload
  become: true

- name: Remove existing mud db if present
  postgresql_db:
    name: mud
    state: absent
    login_user: postgres
  become: true
  become_user: postgres

- name: Create mud db
  postgresql_db:
    name: mud
    state: present
    login_user: postgres
  become: true
  become_user: postgres

- name: Create mud db schema
  postgresql_db:
    name: mud
    state: restore
    target: /tmp/mud.sql
    login_user: postgres
  become: true
  become_user: postgres
